Repository Waste-Relations/Waste-Relations, pull requests merged in 2018-08, with the labels that each got.

#7 small fix with setup file.
  .eslintrc.json
  README.md
  config/config.json
  dev-notes/notes.txt
  dev-notes/tools.txt
  models/index.js
  package-lock.json
  package.json
  routes/apiRoutes.js
  routes/htmlRoutes.js
  server.js
  views/index.handlebars
Labels: bug, ops

#24 added index handlebar file
  config/config.json
  dev-notes/reference files/models.old/example.js
  dev-notes/reference files/models.old/index.js
  dev-notes/reference files/models.old/schema.sql
  dev-notes/reference files/public.old/js/index.js
  dev-notes/reference files/public.old/styles/styles.css
  dev-notes/reference files/routes.old/apiRoutes.js
  dev-notes/reference files/routes.old/htmlRoutes.js
  dev-notes/reference files/views.old/404.handlebars
  dev-notes/reference files/views.old/index.handlebars
  dev-notes/reference files/views.old/layouts/main.handlebars
  dev-notes/wireframe/Waste Relations - basic wireframe.png
  models/example.js
  models/output.json
  models/schema.sql
  models/seed.sql
  models/wastetable.js
  public/css/button.css
  public/css/nav.css
  public/css/style.css
  public/img/logo-v2.gif
  routes/apiRoutes.js
  routes/htmlRoutes.js
  views/charity.handlebars
  views/donation.handlebars
  views/index.handlebars
  views/layouts/main.handlebars
  views/login.handlebars
  views/map.handlebars
  views/pickup.handlebars
  views/profile.handlebars
  views/result.handlebars
  views/search.handlebars
  views/signup.handlebars
Labels: UI

#25 Sequelize CLI Migrations setup
  config/config.json
  migrations/20180811174352-create-waste-item.js
  migrations/20180811182203-allowing.js
  models/index.js
  models/output.json
  models/schema.sql
  models/seed.sql
  models/wasteitem.js
  models/wastetable.js
  package-lock.json
  package.json
  public/css/login.css
  public/css/signup.css
  routes/apiRoutes.js
  routes/htmlRoutes.js
  seeders/20180811174744-demo-wasteitemg.js
  seeders/output.json
  views/index.handlebars
  views/login.handlebars
  views/signup.handlebars
Labels: ops

#29 passport autho
  config/middleware/isAuthenticated.js
  config/passport.js
  models/user.js
  package-lock.json
  package.json
  public/css/style.css
  public/js/login.js
  public/js/search.js
  public/js/signup.js
  routes/apiRoutes.js
  routes/htmlRoutes.js
  server.js
  views/index.handlebars
  views/layouts/main.handlebars
  views/login.handlebars
  views/search.handlebars
  views/signup.handlebars
Labels: backend

#34 adding item to database seems to be working
  config/config.json
  package-lock.json
  package.json
  public/js/additem.js
  routes/apiRoutes.js
  routes/htmlRoutes.js
  views/additem.handlebars
  views/search.handlebars
Labels: backend

#40 created dropoff.js where the model DropOff is defined
  models/dropoff.js
Labels: backend

#42 merging Andrei and Christine work
  .env
  .gitattributes
  .gitignore
  config/config.json
  dev-notes/notes.txt
  models/index.js
  package-lock.json
  package.json
  public/css/result.css
  public/js/additem.js
  routes/htmlRoutes.js
  test/wasteitem.test.js
  views/layouts/main.handlebars
  views/search.handlebars
Labels: backend

#45 post route has been added for dropoff
  .env
  config/middleware/isAuthenticated.js
  package-lock.json
  package.json
  public/css/nav.css
  public/js/additem.js
  public/js/dropoff.js
  routes/apiRoutes.js
  routes/htmlRoutes.js
  views/additem.handlebars
  views/donation.handlebars
  views/dropoff.handlebars
  views/layouts/main.handlebars
  views/search.handlebars
Labels: backend

#50 search is working
  .env
  .gitignore
  README.md
  config/config.json
  config/middleware/isAuthenticated.js
  package.json
  public/js/additem.js
  public/js/dropoff.js
  public/js/search.js
  routes/apiRoutes.js
  routes/htmlRoutes.js
  views/additem.handlebars
  views/dropoff.handlebars
  views/index.handlebars
  views/layouts/main.handlebars
  views/login.handlebars
  views/result.handlebars
  views/search.handlebars
  views/signup.handlebars
Labels: UI, backend

#52 Pull request for reading dropoff database
  .env
  migrations/20180811174352-create-waste-item.js
  package-lock.json
  package.json
  routes/htmlRoutes.js
  views/dropoff.handlebars
Labels: backend

#53 some route status and lint fixes
  .env
  public/css/about.css
  public/css/dropoff.css
  public/css/nav.css
  public/css/profile.css
  public/css/style.css
  public/js/about.js
  public/js/additem.js
  public/js/dropoff.js
  routes/apiRoutes.js
  routes/htmlRoutes.js
  views/about.handlebars
  views/dropoff.handlebars
  views/layouts/main.handlebars
  views/map.handlebars
  views/pickup.handlebars
  views/profile.handlebars
  views/search.handlebars
Labels: enhancement

#58 stuff
  public/css/dropoff.css
  public/css/style.css
  public/js/dropoff.js
  test/dbconnect.test.js
  views/about.handlebars
  views/additem.handlebars
  views/charity.handlebars
  views/dropoff.handlebars
  views/index.handlebars
  views/layouts/main.handlebars
  views/login.handlebars
  views/profile.handlebars
  views/search.handlebars
  views/signup.handlebars
Labels: Critical!, backend

#60 more styling
  views/additem.handlebars
  views/dropoff.handlebars
  views/search.handlebars
Labels: UI

#61 fixed edit bugs
  .env
  public/js/dropoff.js
  views/dropoff.handlebars
Labels: bug
